name: storage


default-extensions:
  DataKinds
  DeriveGeneric
  DisambiguateRecordFields
  DuplicateRecordFields
  FlexibleContexts
  FlexibleInstances
  NoImplicitPrelude
  OverloadedStrings
  StandaloneDeriving
  TypeFamilies
  TypeOperators


dependencies:
  - aeson == 1.*
  - base >= 4.9
  - dotenv == 0.3.*
  - envy == 1.3.*
  - flow
  - process == 1.4.*
  - protolude == 0.1.*
  - selda == 0.1.*
  - selda-postgresql == 0.1.*
  - servant-docs == 0.10.*
  - servant-server == 0.11.*
  - text == 1.2.*
  - wai-cli == 0.1.*


executables:
  # 🚜
  server:
    main: Boot.hs
    source-dirs:
      - app
      - lib

  # 📖
  docs:
    main: Docs.hs
    source-dirs:
      - app
      - lib

  # 🛠
  cli:
    main: Main.hs
    source-dirs:
      - app
      - cli
      - lib
