name: storage


default-extensions:
   DataKinds
   DeriveGeneric
   DisambiguateRecordFields
   DuplicateRecordFields
   FlexibleInstances
   NoImplicitPrelude
   OverloadedStrings
   StandaloneDeriving
   TypeOperators


dependencies:
  - aeson == 1.*
  - base >= 4.9
  - dotenv == 0.3.*
  - envy == 1.3.*
  - flow
  - protolude == 0.1.*
  - selda == 0.1.*
  - selda-postgresql == 0.1.*
  - servant-docs == 0.10.*
  - servant-server == 0.11.*
  - text == 1.2.*
  - wai-cli == 0.1.*
  - warp == 3.*


executables:
  # 🚜
  server:
    main: App.hs
    source-dirs:
      - app
      - lib

  # 📖
  docs:
    main: Docs.hs
    source-dirs:
      - app
      - lib
