name: storage


default-extensions:
   DataKinds
   DeriveGeneric
   DisambiguateRecordFields
   DuplicateRecordFields
   FlexibleInstances
   OverloadedStrings
   StandaloneDeriving
   TypeOperators


dependencies:
  - aeson == 1.*
  - base >= 4.9
  - flow
  - servant-docs == 0.10.*
  - servant-server == 0.11.*
  - warp == 3.*


executables:
  # 🚜
  server:
    main: App.hs
    source-dirs:
      - app
      - lib

  # 📖
  docs:
    main: Docs.hs
    source-dirs:
      - app
      - lib
